
/* eslint-disable */
module.exports = {
    apps: [
        {
            name: "be", // Nest.js backend service
            script: "dist/src/main.js", // Compiled entry point (generated by `npm run build`)
            exec_mode: "cluster",
            instances: "max",
            env: {
                NODE_ENV: "production",
            },
        },
    ],
};
